language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
# command to install dependencies
install: "pip install -r requirements_dev.txt"
# command to run tests
script: make test
before_install:
  - pip install codecov
after_success:
  - codecov